### ISSUE TITLE
PHPBack not installing, either error #6 or 500 error

### ISSUE THREAD

**Issue by tsiguy96** [ivandiazwm/phpback#105]
Hi, I am trying to install PHPBack, and have been trying for a very long time!

Essentially, no method of installation works.  When I leave the database spot blank, I get error #6, stating that phpback database cant be made and I need to make my own database.  But when I do that, and give the user all privileges of that database, then enter the appropriate information onto the phpback installation, I go straight to a 500 error on index2. 

I have tried most every option to get this to work and nothing actually works. Any ideas why it wont let me manually create a database and use that?
Thanks!

**Comment by DanielRuf** [comment]
Please provide the relevant errorlog entries.

**Comment by ivandiazwm** [comment]
I think this has something to with the permission to the `install` folder. We are having a similar issue with  inMotion hosting due to the permissions. Check if you can change the folder permission to 755.

**Comment by drveresh** [comment]
@tsiguy96  Please reopen this issue if it still persists.
