### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by GaneshKandu** [ivandiazwm/phpback#108]
Hi,
Trying to Install phpback on my machine

- php 5.3
- mysql 5.5
- apache Apache/2.2.31 (Unix)

i have given recursively writable on install folder so that script can delete it self

 but when i am clicking on install/index2.php on second step of installation for email configuration

script deletes install2.php and index2.php and redirect to inistall2.php whereas its not exist and phpback redirect to install.php again and not deleting install1.php ,index.php and database_tables.sql but phpback is installed successfully #61 #56

after installation Getting this error on  [{{url}}/admin/system](http://localhost/phpback/admin/system)

php 5.3 is minimum requirement you mentioned on README.md

**Parse error**: syntax error, unexpected '[' in **vendor/visualappeal/php-auto-update/src/AutoUpdate.php** on line **426**

**Comment by GaneshKandu** [comment]
#87 
Parse error: syntax error, unexpected '[' in vendor/visualappeal/php-auto-update/src/AutoUpdate.php on line 426\
short array tag does not supports on php 5.3 supports in php 5.4

php 5.3 is minimum requirement you mentioned on README.md

**Comment by ivandiazwm** [comment]
Interesting, it looks like we have to update the readme. However, I was planning to remove that library anyway.

**Comment by DanielRuf** [comment]
PHP 5.3 (and all versions up until 5.6 included) should not be used anymore.

**Comment by ivandiazwm** [comment]
Readme updated
