### ISSUE TITLE
Add Cloudron to install instructions

### ISSUE THREAD

**Issue by nebulade** [ivandiazwm/phpback#109]
Hi there,

thanks for the great app, I have made a https://cloudron.io package for it some time ago. Would it be possible to add either the appstore link https://cloudron.io/store/org.phpback.cloudronapp.html or the install button to the readme?

[![Install](https://cloudron.io/img/button.svg)](https://cloudron.io/button.html?app=org.phpback.cloudronapp)

If possible, I can create a pull request. Thanks!

**Comment by ivandiazwm** [comment]
Yeah sure, feel free to create the PR.

**Comment by nebulade** [comment]
Now merged.
