### ISSUE TITLE
integrate Travis / CircleCI

### ISSUE THREAD

**Issue by DanielRuf** [ivandiazwm/phpback#119]
The tests should be run on any commit and pull request.

**Comment by ivandiazwm** [comment]
We have integration tests made with selenium. We were not able to integrate them correctly with codeship or travis ci.
I'm planning to update code and use a more modular class architecture, enabling me to use unit testing.

**Comment by DanielRuf** [comment]
At least Travis and CircleCI (and others) provide support for Selenium tests (through thirdparty integrations).

https://circleci.com/integrations/saucelabs/

https://docs.travis-ci.com/user/gui-and-headless-browsers/

https://www.browserstack.com/automate/travisci

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/ivandiazwm/phpback/issues/16
