### ISSUE TITLE
What is the list of cookies that PHPBack v1.3.2 software uses ?

### ISSUE THREAD

**Issue by raykai** [ivandiazwm/phpback#133]
Hi,
To comply with cookie laws i need to list the names of the cookies that my site uses and say the purpose of each cookies and the duration that the cookies stay on a user's device.

To this end, i am wondering what cookies PHPBack v1.3.2 software users on our servers?

i would need the names of the cookies, its duration, and their purposes for each cookies.

some help on this would be appreciated.

**Comment by DanielRuf** [comment]
You can try a search for `setcookie` and `cookie` in general in the source code.

**Comment by drveresh** [comment]
@raykai  Please reopen this issue if you still have concerns around cookies.
