### ISSUE TITLE
How to disable rewrite?

### ISSUE THREAD

**Issue by DrLynix** [ivandiazwm/phpback#139]
Hi,

I just set up phpback on my server (with PHP 7) and it does works well. Until i try to login.

I'm using nginx as a web server and it doesn't handle .htaccess files which enable rewrite rules.

Is it possible to not use URL rewrite with phpback?

Thanks

**Comment by DanielRuf** [comment]
Probably no. There are modules and instructions on the internet how you van use the rewrite rules and .htaccess with nginx.

**Comment by murmelbahn** [comment]
Can someone help me with the rewrite rules for nginx?

**Comment by DanielRuf** [comment]
You can use either a module which adds support for .htaccess in Nginx or you may have to port the rules manually.

Sorry, never did the porting stuff in bigger projects.

**Comment by murmelbahn** [comment]
Okay, then i have to port them. Which of all the htaccess files is responsible for the error mentioned by DrLynix?

**Comment by murmelbahn** [comment]
Oh, i've figgured out by myself.
I've created a new location in my config file under /etc/nginx/sites-enabled

location /$path/to/phpback {
if (!-e $request_filename){ rewrite ^(.*)$ /$path/to/phpback/index.php?/$args; }
    }

It seems like everything is working now.

**Comment by DanielRuf** [comment]
Awesome =)

**Comment by DanielRuf** [comment]
Closing as I think the issue is resolved.
