### ISSUE TITLE
DB Connections Issues After Updating CSS Files

### ISSUE THREAD

**Issue by drveresh** [ivandiazwm/phpback#155]
I am getting the below error frequently whenever I update CSS files.  How the DB and CSS updates are related here?

```
A Database Error Occurred
Unable to select the specified database: <db_name>

Filename: core/Loader.php

Line Number: 347
```

**Comment by drveresh** [comment]
Also, STOP displaying database_name or any other credential information on UI.  It is absolutely not recommended!

**Comment by DanielRuf** [comment]
I guess this is only a technical issue with your hoster.

Closing as we did not get any further details to reproduce this.
