### ISSUE TITLE
Upgrade Failed

### ISSUE THREAD

**Issue by Leinad4Mind** [ivandiazwm/phpback#158]
AUtomatic Upgrade from 1.3.1 to 1.3.2 fails because /vendor/vierbergenlars/php-semver/src/vierbergenlars/SemVer/internal.php Line 7 uses Object as a class name, and thats a special word, that can't be used as class name.

**Comment by Leinad4Mind** [comment]
Related: https://github.com/vierbergenlars/php-semver/commit/be22b86be4c1133acc42fd1685276792024af5f9

**Comment by DanielRuf** [comment]
Please provide all relevant details like your PHP version.

**Comment by DanielRuf** [comment]
https://github.com/vierbergenlars/php-semver/releases/tag/3.0.2

**Comment by DanielRuf** [comment]
Please try deleting composer.lock and run `composer install`.

https://github.com/ivandiazwm/phpback/blob/master/composer.lock

The linked dependency is a deep peerdependency and comes from the lockfile which was updated 3 years ago.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
