### ISSUE TITLE
Can enter over 100 chars title

### ISSUE THREAD

**Issue by mzch** [ivandiazwm/phpback#168]
Hi,

Now uses can post an invalid idea with too long title, over 100 chars.
This is a bug at line 26 in application/views/home/post_idea.php.
Please change 'max="100"' to 'maxlength="100"'.

**Comment by DanielRuf** [comment]
This seems to be like this for a few years now. Do you want to proide a PR for this?

https://github.com/ivandiazwm/phpback/commit/5c1d31b6212e0641d88e611b8b853fd5758cd466

**Comment by DanielRuf** [comment]
Hi @mzch,

thanks for reporting this bug.

This seems to be like this for a few years now. Do you want to provide a PR for this?

https://github.com/ivandiazwm/phpback/commit/5c1d31b6212e0641d88e611b8b853fd5758cd466

**Comment by DanielRuf** [comment]
Hi @mzch,

thanks for reporting this bug.

This seems to be like this for a few years now.
Do you want to provide a PR for this?

https://github.com/ivandiazwm/phpback/commit/5c1d31b6212e0641d88e611b8b853fd5758cd466

**Comment by mzch** [comment]
Hi,

created. :) Plz refer PR #169

**Comment by drveresh** [comment]
PR #169 is merged.  Thanks @mzch and @DanielRuf.
