### ISSUE TITLE
phpback is not available on cloudron store

### ISSUE THREAD

**Issue by SamirFarhat** [ivandiazwm/phpback#170]
phpback is not available on cloudron store, was it retired ?

**Comment by DanielRuf** [comment]
I can see it at https://cloudron.io/store/org.phpback.cloudronapp.html

Anyways, please ask the Cloudron support.

**Comment by SamirFarhat** [comment]
Yes, but when you go to the store, i can'tfind it? M

**Comment by DanielRuf** [comment]
> please ask the Cloudron support
