### ISSUE TITLE
Security Vulnerabilties

### ISSUE THREAD

**Issue by paragonie-scott** [ivandiazwm/phpback#2]
PHPBack seems to build atop an older version of CodeIgniter, which has numerous security vulnerabilities:

1. http://www.securityfocus.com/archive/1/532384
2. https://scott.arciszewski.me/research/view/php-framework-timing-attacks-object-injection

Please update `system/` to the latest version of CodeIgniter.

**Comment by ivandiazwm** [comment]
Yes, it looks like this need to be updated. I'm going to be looking at this as soon as possible. Thank you, I really appreciate it.

**Comment by ivandiazwm** [comment]
Codeigniter has been updated to version 2.2.5
