### ISSUE TITLE
No input file specified issue

### ISSUE THREAD

**Issue by GamesPress** [ivandiazwm/phpback#21]
Followed all the instructions and it looks like it installs ok however when I goto admin or login or post new idea all i get is No input file specified.

featuredstreamer.com/feedback/

**Comment by ivandiazwm** [comment]
Do you have the [.htaccess file](https://github.com/ivandiazwm/phpback/blob/master/.htaccess) ?
The problem is there, could you try to change the last line to `RewriteRule ^(.*)$ index.php?/$0` ?

Thanks!
-Ivan

**Comment by GamesPress** [comment]
Hi Ivan,

Made the edit to the .htaccess file and it looks like its all working fine now.

Kind Regards
Paul.
