### ISSUE TITLE
Registration at "PHPBack Feedback" impossible

### ISSUE THREAD

**Issue by jazzcrack** [ivandiazwm/phpback#22]
Unfortunately you can not successfully register at  "PHPBack Feedback" (www.phpback.org/feedback/). I would love to give my feedback to you.

**Comment by ivandiazwm** [comment]
I think I forgot to update it to the last version.  I'll fix it as soon as I can. Thanks!

**Comment by ivandiazwm** [comment]
I have updated it to the last version. Registration should be possible now
