### ISSUE TITLE
idea accounting even if there are not considered by admin

### ISSUE THREAD

**Issue by MarieCocci** [ivandiazwm/phpback#25]
Hello (again)

When I was testing, I create an idea and it appears in the right list. "1" appears for the category but as it wasn't validated it doesn't appear on the page...

Thank in advance for your reply

Regards

**Comment by ivandiazwm** [comment]
It looks like there's being considered all the ideas (even not approved) when calculating the number for the category. It should be updated to count all non-under-review ideas.

Thanks for the suggestion, we will add it in next releases.

**Comment by MarieCocci** [comment]
ok thank you a lot

**Comment by ivandiazwm** [comment]
Solved in e696d24aef38113587871ed853fef16cf2545ae6
