### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Jessar1994** [ivandiazwm/phpback#27]
When i have upload all files (phpback_v1.2.0 files from http://www.phpback.org/) to my web hosting company and fill in the details.
for PHPBack installation 

(MySQL hostname, MySQL username and password, MYSQL database) & admin name, email, password and click proceed i moving to the next step.

Then i fill in the details there. 
Feedback title, Mail email, leaving recaptcha blank because I don't know how it works yet.,
and click proceed.  when i came to http://feedback.supportportalen.mobi/install/install2.php i get error.

(HTTP 404-error), im going back to my ftp and take a look at the install map.
The install map is empty. Why?

Then if i go to http://feedback.supportportalen.mobi/ i get error: 

A Database Error Occurred  
Unable to connect to your database server using the provided settings.
Filename: core/Loader.php
Line Number: 347

Can you explain how I can solve the problem?

https://dl.dropboxusercontent.com/u/42214358/supportportalen/errors/error_install_phpback.mp4

**Comment by ivandiazwm** [comment]
Hi Jessar1994,
The installation process automatically deletes all the installation files.

Please, take a look to the file `application/config/database.php` (it's generated by the installation). It should contain all the information to connect to the database and the mysql server: https://github.com/ivandiazwm/phpback/wiki/How-To-install#error-1-config-file-could-not-be-created

I'd recommend you delete all the tables on the database (or delete it and create a new one), delete the database.php file if exists and upload the installation files aging.

I'm trying to reproduce this issue and I'll tell you has soon as I have updates o this, please stay tuned.

**Comment by Jessar1994** [comment]
I have tried that, same error :/

**Comment by ivandiazwm** [comment]
Please, verify that `database.php` has the correct values for connecting to the database.

I've also noticed you've got the *No input file specified* issue. Please, try this: https://github.com/ivandiazwm/phpback/issues/21

**Comment by Jessar1994** [comment]
It has the correct values.

I have a php file to test the connection: http://feedback.supportportalen.mobi/connsucess.php

I have change the last line to RewriteRule ^(.*)$ index.php?/$0 in the .htaccess file.

still have the error messages: 

A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 347

I will talk to Binero, and ask if there is problem with mysql database.

**Comment by ivandiazwm** [comment]
Try changing `$db['default']['db_debug'] = TRUE;` to `$db['default']['db_debug'] = FALSE;` in database.php

**Comment by Jessar1994** [comment]
Okey, now this error gone: 
A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 347

But when i go to my site: http://feedback.supportportalen.mobi/ i get error: https://dl.dropboxusercontent.com/u/42214358/supportportalen/errors/error_site.PNG

**Comment by Jessar1994** [comment]
if i send you a email with details on my ftp login and mysql login (with Read / write permissions) can you install phpback for me?

I can't get it to work correctly.

**Comment by ivandiazwm** [comment]
Sure no problem.
Could you also try to change the dbdriver? I mean this `$db['default']['dbdriver'] = "mysql";` to this `$db['default']['dbdriver'] = "mysqli";`

**Comment by Jessar1994** [comment]
now it looks normal, but now I can not login to the admin panel.
It says, Email or password are incorrect, I have written down my login information in my excel.

gets crazy on this -.-
