### ISSUE TITLE
Unsalted crypt(), other oddities

### ISSUE THREAD

**Issue by df-5** [ivandiazwm/phpback#3]
Not really secure and also PHP will throw a notice for this:
`PHP Notice:  crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.`

**Comment by ivandiazwm** [comment]
Thank you for noticing this, I'll be looking at it as soon as I can.

**Comment by ivandiazwm** [comment]
crypt function has been updated
