### ISSUE TITLE
SECURITY: generate random using openssl or urandom

### ISSUE THREAD

**Issue by bbalet** [ivandiazwm/phpback#32]
The way you generate random string is not safe. You should rely on PHP Internal/openssl
See how I revisited you code:
https://github.com/bbalet/phpback/blob/e9b2415f1d845cb607b156e65f236a5f4f359dd4/install/install1.php#L130

**Comment by ivandiazwm** [comment]
Yes, this need to be added to the hashing library and we should use that one in the installation to avoid repeated code. I'm opening a PR with this changes.
