### ISSUE TITLE
Code Quality: comment and PSR naming convention

### ISSUE THREAD

**Issue by bbalet** [ivandiazwm/phpback#34]
If you want to attract contributors, you should improve the quality of your code right now because it difficult to understand and to maintain:
* Adopt Camel case names for methods with GOOD names.
* Use PHPDoc blocks for methods and files.
* Write more comments.

**Comment by ivandiazwm** [comment]
Yes you're right. The code is a bit old and we are now constantly making updates: automation tests, passing all functions to camelCase with better names, refactoring logic, improving documentation, removing unnecessary code.
We're still working on code refactor and it hasn't been completed yet (we have pending tasks related)
 
Thanks for notice this, your feedback has been really helpful!
