### ISSUE TITLE
Usability: use hand pointer when mouse is over tabs of second level

### ISSUE THREAD

**Issue by bbalet** [ivandiazwm/phpback#35]
In admin panel, when I select:
* Ideas and Comments
* Users Management
* System Settings

The secondary tabs (eg "New Ideas" of "Ideas and Comments") doesn't look clickable for user (I'm not speaking from a technical perspective here, but from a user point of view). You should change the mouse pointer icon to hand for these tabs.

**Comment by ivandiazwm** [comment]
Solved in d30cdcd3be2a43ceda065f4ff880f4d5198376b8
