### ISSUE TITLE
ERROR 404 - Not Found!

### ISSUE THREAD

**Issue by worp1900** [ivandiazwm/phpback#40]
Extracting the files to our web root and having installed the application, we now encounter a 404 if we want to log in, post an idea, etc.

urls include but might not be limited to:
/home/postidea
/home/login
/home/search

Apache Access log reports:
"GET /home/postidea HTTP/1.1" 404 2097 "http://yourServer.de/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
"GET /favicon.ico HTTP/1.1" 200 3306 "http://yourServer.de/home/postidea" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
"GET /home/login HTTP/1.1" 404 2098 "http://yourServer.de/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
"POST /home/search HTTP/1.1" 404 2097 "http://yourServer.de/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"

Issue seems unaffected by browser, tested with up2date FireFox, Apache und IE.

I assume I did something wrong, maybe the server setup is wrong. I don't know my way around CI enough to figure it out myself.

**Comment by ivandiazwm** [comment]
I think this could be a .htaccess issue. (like [this one](https://github.com/ivandiazwm/phpback/issues/21)).

I have researched a bit about this and I've found that it's a common issue if you use FastCGI. Please try this one:
http://stackoverflow.com/questions/3752609/codeigniter-404-page-not-found-but-why/3769389#3769389

I'll be keeping an eye on this issue. Let me know if that worked.
Thanks,
Ivan.

**Comment by worp1900** [comment]
Thanks for the hint, didn't think of the .htaccess before. I will try it tonight and get back to you

**Comment by worp1900** [comment]
Yes, it was an .htaccess issue. The wrong permissions were given so Apache behaved according to default, which, on our server, does not include rewrite rules.

Issue can be closed. Thank you for your support =)
