### ISSUE TITLE
phpBack.org is marked as harmfull

### ISSUE THREAD

**Issue by ChristophLindemann** [ivandiazwm/phpback#41]
Google is flagging www.phpback.org as harmfull: "This site may harm your computer."

**Comment by ivandiazwm** [comment]
This was caused by a damaged jquery plugin used in our main website. We've already solved the problem and informed google. The message should be gone within two or three days.

**Comment by ivandiazwm** [comment]
Restored.

**Comment by ChristophLindemann** [comment]
Same problem with bing:


WARNING!

This site might download malicious software that can harm your computer. Learn More

We recommend you choose another result or you can go to this site anyway.

To learn more about why this URL was marked as malicious, please visit the Bing Site Safety page.
