### ISSUE TITLE
phpBack.org is marked as harmfull on bing

### ISSUE THREAD

**Issue by ChristophLindemann** [ivandiazwm/phpback#42]
same as #41 but on bing

> WARNING!
>
> This site might download malicious software that can harm your computer. [Learn More](http://go.microsoft.com/fwlink/?LinkID=617176)
> We recommend you choose another result or you can go to this site anyway.
> To learn more about why this URL was marked as malicious, please visit the [Bing Site Safety](http://www.bing.com/toolbox/bing-site-safety?url=http%3a%2f%2fwww.phpback.org%2f) page.

http://www.bing.com/toolbox/bing-site-safety?url=http%3a%2f%2fwww.phpback.org%2f

> ## Site Safety Report for http://www.phpback.org/ 
> ### URL Status
> The URL is currently classified as suspicious due to the following detection types:
> - Malware Network Reference
> - Malicious JavaScript
> - Indications of malicious activity.
> - Malware Found on Adjacent Pages
> 
> Suspicious content was last detected at this URL on 2/15/2016.
> ### Scan Information
> This URL was last scanned on 3/14/2016.
> We have scanned this URL 26 time(s) over the past 30 days.

**Comment by ivandiazwm** [comment]
This is not happening any more. Thanks for reporting it.
