### ISSUE TITLE
Missing install scripts from 1.2.0

### ISSUE THREAD

**Issue by ChristophLindemann** [ivandiazwm/phpback#44]
The install folder of phpback_v1.2.0.zip is empty.

So the steps described in the installation guide do not work.

**Comment by sslopek** [comment]
Where did you get the zip from?  Both downloads for the v1.2 release seem to have the proper files: [https://github.com/ivandiazwm/phpback/releases](https://github.com/ivandiazwm/phpback/releases)

**Comment by ivandiazwm** [comment]
I'm so sorry. It looks like the download file on the website was not updated. Thanks for reporting this, Solved!
