### ISSUE TITLE
 I get a (HTTP 404-error) during the install.

### ISSUE THREAD

**Issue by danieljavas** [ivandiazwm/phpback#47]
When i have upload all files (phpback_v1.2.0 files from http://www.phpback.org/) to my local web server (IIS) and fill in the details.

I fill index1.php
(MySQL hostname, MySQL username and password, MYSQL database) & admin name, email, password and click proceed i moving to the next step.

Then i fill in the details there. 
Feedback title, Mail email, leaving recaptcha blank because I don't know how it works yet.,
and click proceed. I get a (HTTP 404-error). 

The installation creates the database but it doesn't creates any entries on the tables. 
![screenshot1](https://cloud.githubusercontent.com/assets/17772946/13688127/4957a29a-e6e5-11e5-8cdf-3b81b1fdb62e.png)
![screenshot2](https://cloud.githubusercontent.com/assets/17772946/13688126/495769ba-e6e5-11e5-88eb-8aeacdc538ac.png)

**Comment by sslopek** [comment]
Currently, the application is only set up to run on apache web servers.  If you create a file called 'web.config' in the main folder of the website with the following code (or just add the `<rewrite>...<rewrite>` section to the existing web.config), it should allow IIS to work the same.  I just used this for an install on IIS, and I'll add it to the project after I test it a bit more.

**web.config**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Rewrite to index.php">
                    <match url="index.php|robots.txt|images|test.php" />
                    <action type="None" />
                </rule>
                <rule name="Rewrite CI Index">
                    <match url=".*" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" pattern="^.+\.(css|js|jpg|jpeg|png|gif|ico|htm|html|eot|woff|ttf|svg|txt)$" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php/{R:0}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration> 
```

[http://stackoverflow.com/questions/5408111/codeigniter-2-on-iis-with-web-config-file](http://stackoverflow.com/questions/5408111/codeigniter-2-on-iis-with-web-config-file)

**Comment by danieljavas** [comment]
Thanks, is Working now, but I have other issue, I don't have any entries on the Database the users table is empty, i cannot login on the admin or the regular users page.

**Comment by sslopek** [comment]
If you have a newer version of MySQL, this is probably the same issue as #48.  For now, you can disable strict mode on the database:

"my.ini" file inside MySQL installation directory
```
# Set the SQL mode to strict
sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
```
Replace with:
```
sql-mode="NO_ENGINE_SUBSTITUTION"
```

After you restart the database with STRICT_TRANS_TABLES disabled, I recommend deleting the phpback database and the website directory, then start a clean install.

**Comment by danieljavas** [comment]
Perfect!, Its working, Thanks a lot!
