### ISSUE TITLE
I get a -1 after deleting an idea.

### ISSUE THREAD

**Issue by Leinad4Mind** [ivandiazwm/phpback#52]
I've create an idea and deleted the idea and now I've a -1 on the category.

**Comment by Leinad4Mind** [comment]
This havent solve the problem.

If I create an Idea and delete it without approve first. It gets a -1.

And if I approve, it gets 1, then If I change the status to Refused, it change to 0. Then if I remove the refused idea, it gets -1.

**Comment by ivandiazwm** [comment]
Yes, now it's fixed

**Comment by Leinad4Mind** [comment]
The fix only fix it partially and have create another problem:

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: label_change_status</p>
<p>Filename: home/view_idea.php</p>
<p>Line Number: 102</p>

After I click on Approve Idea this error appears on the button.

The other problem that this fix doesnt solved is when I put the idea as refused, it goes to 0, it shouldnt! Because after that If I delete the idea it goes to -1.
