### ISSUE TITLE
Ideas do not appear on front page

### ISSUE THREAD

**Issue by nerai** [ivandiazwm/phpback#55]
I've created a few 'ideas', using both admin and non-admin accounts. The ideas are visible in the admin/ideas page. I can also open them and vote on them.

However, no ideas show up in the front page. "Last Completed Ideas" etc. are all blank. All ideas are in the (sole existing) category 'foo', but the 'home/category/1/foo' page is empty, too.

My understanding is that the ideas should be visible somewhere.

**Comment by ivandiazwm** [comment]
Ideas always need to be approved by an admin in order to appear in the home page.
When you go to `/admin/ideas` you'll see the new ideas that have pending approval. When you enter the idea page, you have to click in the green button "Approve Idea"

**Comment by nerai** [comment]
Thank you for the quick response! Should the ideas be visible in the category page, or do they need to be approved for that, too?

**Comment by ivandiazwm** [comment]
Yes, An idea won't be listed in its category page or home page if it isn't approved by an admin.

**Comment by nerai** [comment]
I see. That was unclear to me - maybe it could be made more obvious in the user interface.

Thank you and feel free to close this ticket.

**Comment by ivandiazwm** [comment]
Of course, I think maybe moving the ideas section as home page for admin instead of logs, change the title from "New Ideas" to "Ideas waiting for approval" could help.

I'll be adding that UX issue as something to be improved in our internal trello board

Thanks!

**Comment by fbrnc** [comment]
Hi @ivandiazwm,
I ran into the same issue until I found this issue. I was wondering if there's an easy way to skip this step and have all ideas be auto-approved. We want to use this tool internally and I'd like every idea to show up right away.
Cheers,
Fabrizio

**Comment by ivandiazwm** [comment]
It is not possible right now. But I will added in a future release (it not a hard change). However, you can temporarily change the code if you wish:
You can edit [this file](https://github.com/ivandiazwm/phpback/blob/master/application/models/post.php#L60):

```
    public function add_idea($title, $content, $author_id, $category_id){
        $author_id = (int) $author_id;
        $category_id = (int) $category_id;
        if($author_id < 1 || $category_id < 1) return false;
        $data = array(
	   			'title' => $title,
	   			'content' => $content,
	   			'authorid' => $author_id,
	   			'date' => date("d/m/y H:i"),
	   			'votes' => '0',
	   			'comments' => '0',
	   			'status' => 'considered', //Change new => considered
	   			'categoryid' => $category_id,
			);
        $this->db->insert('ideas', $data);

        //Add this two lines
        $category = $this->get_row_by_id('categories', $category_id);
        $this->update_by_id('categories', 'ideas', $category->ideas + 1, $category->id);

      	$this->log($this->lang->language['log_new_idea'] . ": $title", "user", $author_id);
        return true;
    }

```

**Comment by fbrnc** [comment]
Thanks for the fast response, @ivandiazwm. Your suggestion works great. Looking forward to see this in the next release so I don't need to do manual changes to my version :)
