### ISSUE TITLE
Parse error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by benodilo** [ivandiazwm/phpback#56]
Hi,

Thks for this application.
I tried to install it from 1.3 et 1.2 but I have a message error in administration page : 
Parse error: syntax error, unexpected '[' in /var/www/html/phpback/vendor/visualappeal/php-auto-update/src/AutoUpdate.php on line 362

Best regards 
PHP 5.3.8
Mysql  5.5.15
Apache/2.2.9 (Fedora)

**Comment by ivandiazwm** [comment]
We're having issues with the AutoUpdate script we added. I'll be adding an update tutorial in the wiki page soon.

**Comment by benodilo** [comment]
Hi,

I have download phpback 1.3.1, this problem already existe and in zip file the .htaccess is mising ;)

Best regards.

**Comment by ivandiazwm** [comment]
It looks like the .htaccess was missing in that zip file. I have updated it. Now it's working. Sorry for the inconvenience

**Comment by benodilo** [comment]
Nothing new in wiki :(
I undertand it's a problem with update script but what I can do ?

Best regards !

**Comment by ivandiazwm** [comment]
Oh, It's here:
https://github.com/ivandiazwm/phpback/wiki/Upgrade-Guide

**Comment by DanielRuf** [comment]
Closing as resolved.
