### ISSUE TITLE
Enable cross domain

### ISSUE THREAD

**Issue by nguyenquynhan** [ivandiazwm/phpback#81]
Hi Guys
Where do we enable cors domain?

**Comment by ivandiazwm** [comment]
What are you exactly trying to do? Perhaps in .htaccess file?

**Comment by nguyenquynhan** [comment]
I can do that in .htaccess. Thanks!
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"

**Comment by ivandiazwm** [comment]
awesome!
